language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly

matrix:
    allow_failures:
        - php: nightly
        - php: 5.6 #See https://github.com/schmittjoh/serializer/issues/283

before_script:
  - cp ./app/config/parameters.yml.dist ./app/config/parameters.yml
  - composer install --prefer-source

after_failure: "cat /home/travis/build/gimler/symfony-rest-edition/app/logs/test.log"

script: phpunit -c app --coverage-clover build/logs/clover.xml

after_script:
  - ./bin/test-reporter

addons:
  code_climate:
    repo_token: c7cd1ff9a23bdc944f020a692bcee23e19844c981e6ee9643240461b7d250706
