# run when executing tests
imports:
    - { resource: config_dev.yml }

framework:
    test: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Database config override
# have the tests use sqlite instead of the "real" database
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db

# Speed up local tests
liip_functional_test:
    cache_sqlite_db: true
