# run when executing tests
imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    #profiler:
    #   enabled: false # false in regular Symfony REST Edition

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Database config override
# have the tests use sqlite instead of the "real" database
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db

# Speed up local tests
liip_functional_test:
    # if the caching is on, the load(..) method of a fixture only effectively gets run once
    # so exporting the defined entities directly through a static array will not work
    # see LoadUserData for a workaround
    cache_sqlite_db: true
